#!/bin/bash
#
# Funciones usadas por los alias de ~/.gitconfig.
# Se cargan con `. ~/.githelpers` desde los propios alias.

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%C(bold blue)<%an>%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR}$REFS $SUBJECT"

# Log en una línea por commit, con las columnas alineadas.
# `column -t -s '}'` parte por el separador que metemos en $FORMAT.
pretty_git_log() {
    git log --graph --abbrev-commit --date=relative --pretty="tformat:${FORMAT}" "$@" |
        column -t -s '}' |
        less -FXRS
}

# Borra ficheros sin trackear. Enseña primero qué se va a cargar y pide
# confirmación: `git clean -fd` no tiene vuelta atrás.
remove_untracked_files() {
    local files
    files=$(git clean -nd "$@")

    if [ -z "$files" ]; then
        echo "No hay ficheros sin trackear que borrar."
        return 0
    fi

    echo "$files"
    echo
    printf "¿Borrar lo de arriba? [y/N] "
    read -r reply
    case "$reply" in
        [yY]) git clean -fd "$@" ;;
        *)    echo "Cancelado." ;;
    esac
}
