#!/bin/bash
#
# Functions used by the aliases in ~/.gitconfig.
# They are loaded with `. ~/.githelpers` from the aliases themselves.

HASH="%C(yellow)%h%Creset"
RELATIVE_TIME="%Cgreen(%ar)%Creset"
AUTHOR="%C(bold blue)<%an>%Creset"
REFS="%C(red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH}$RELATIVE_TIME}$AUTHOR}$REFS $SUBJECT"

# One line per commit, with the columns aligned.
# `column -t -s '}'` splits on the separator baked into $FORMAT.
pretty_git_log() {
    git log --graph --abbrev-commit --date=relative --pretty="tformat:${FORMAT}" "$@" |
        column -t -s '}' |
        less -FXRS
}

# Delete untracked files. Shows what is about to go and asks first:
# `git clean -fd` has no undo.
remove_untracked_files() {
    local files
    files=$(git clean -nd "$@")

    if [ -z "$files" ]; then
        echo "No untracked files to delete."
        return 0
    fi

    echo "$files"
    echo
    printf "Delete the above? [y/N] "
    read -r reply
    case "$reply" in
        [yY]) git clean -fd "$@" ;;
        *)    echo "Cancelled." ;;
    esac
}
